### ISSUE TITLE
Modifications in slayerPytorch

### ISSUE THREAD

**Issue by yuweiDu** [uzh-rpg/snn_angular_velocity#8]
Could you please explain the modifications in SLAYER  that you have made? For instance, I can find slayersnn.loss (which I can't find in the moodified version)  in original slayerPytorch. THANK YOU!

**Comment by magehrig** [comment]
Hi @yuweiDu

First I used a much earlier SLAYER version and cleaned up some code and made it self-contained (no change in functionality). I added a custom ref Kernel: https://github.com/uzh-rpg/snn_angular_velocity/blob/e95f2b96c83fb61c1fe45f43b0112a610bcad3f0/slayerpytorch/src/slayer.py#L72-L80

Otherwise, the rest should be more or less the same

**Comment by celynw** [comment]
Hi - I compared to the original SLAYER repository, and it seems that you also modified the backward pass of ` _spikeFunction`. I'm interested in the difference in results because of this, how significant is it?

https://github.com/uzh-rpg/snn_angular_velocity/blob/e95f2b96c83fb61c1fe45f43b0112a610bcad3f0/slayerpytorch/src/slayer.py#L505-L510

**Comment by magehrig** [comment]
@celynw 

It should not make a difference in principle because the pdfTimeConstant is [scaled with the threshold anyway](https://github.com/uzh-rpg/snn_angular_velocity/blob/e95f2b96c83fb61c1fe45f43b0112a610bcad3f0/slayerpytorch/src/slayer.py#L497). The only difference is the multiplication with [tauRho](https://github.com/uzh-rpg/snn_angular_velocity/blob/e95f2b96c83fb61c1fe45f43b0112a610bcad3f0/model/base.py#L128) which is in fact a constant. So you can ignore those comments and use the default slayer config and maybe adjust the pdfScale accordingly (it is anyway something that you might have to tune).

Tbh I think this part is the most arbitrary part of the whole slayer framework. The backward pass is quite the heuristic, and the scaling is relatively arbitrary.

**Comment by celynw** [comment]
Ok, thank you!
